---
#
#
# One time Configuration Only
#
#
#


agent:
    #- nimblestorage::create
    - nimblestorage::cleanup

iscsiadm:
  config: 
    ensure: present
    port: 3260
    target: 192.168.121.6
    user: "%{alias('chap.username')}"
    password: "%{alias('chap.password')}"

multipath: 
  config: true

chap:
  ensure: absent
  username: chapuser
  password: password_25-24
  systemIdentifier: test-chap-account # Puppet identifies this as its name of the instantiated resource in manifest.

initiator:
  ensure: absent
  groupname: "%{::fqdn}-ig"
  label: "%{::hostname}-%{::clientcert}"
  #ip_address: "%{::ipaddress}"
  ip_address: "*"
  access_protocol: "iscsi"
  description: "This is a puppet initiator group"
  subnets:
   - Management


#
#
#
#   Manage Arrays using the below maps
#
#

protection_template:
  prot-temp-1:
    ensure: absent
    schedule_list:
      - name: schedule-1-1
        num_retain: 30
      - name: schedule-2-1
        num_retain: 60
      - name: schedule-3-1
        num_retain: 90
      - name: schedule-4-1
        num_retain: 120
  prot-temp-2:
    ensure: absent
    schedule_list:
      - name: schedule-1-2
        num_retain: 120
      - name: schedule-2-2
        num_retain: 120


volume_collection:
  vol-coll-1:
    ensure: absent
    prottmpl_name: prot-temp-2
  vol-coll-2:
    ensure: absent
    prottmpl_name: prot-temp-1
  vol-coll-3:
    ensure: absent
    prottmpl_name: prot-temp-2


volumes:
  volume_1:
    ensure: absent
    name: "%{::hostname}-vol-1"
    size: 210m
    description: sample
    perfpolicy: default
    force: true
    online: true
    vol_coll: vol-coll-2
  volume_2:
    ensure: absent
    name: "%{::hostname}-vol-2"
    size: 20m
    description: sample
    perfpolicy: default
    force: true
    online: true
    vol_coll: vol-coll-1
  volume_3:
    ensure: absent
    name: "%{::hostname}-vol-3"
    size: 20m
    description: sample
    perfpolicy: default
    force: true
    online: true
    vol_coll: vol-coll-1

access_control:
  volume_1:
    ensure: present
    volume_name: "%{alias('volumes.volume_1.name')}"
    chap_user: "%{alias('chap.username')}"
    initiator_group : "%{alias('initiator.groupname')}"
    apply_to: both
  volume_2:
    ensure: present
    volume_name: "%{alias('volumes.volume_2.name')}"
    chap_user: "%{alias('chap.username')}"
    initiator_group : "%{alias('initiator.groupname')}"
    apply_to: both
  volume_3:
    ensure: present
    volume_name: "%{alias('volumes.volume_3.name')}"
    chap_user: "%{alias('chap.username')}"
    initiator_group : "%{alias('initiator.groupname')}"
    apply_to: both

mount_points:
  volume_1:
    ensure: absent
    target_vol: "%{alias('volumes.volume_1.name')}"
    mount_point: /home/agent/vol_1
    fs: ext3
    label: vol1
  volume_2:
    ensure: absent
    target_vol: "%{alias('volumes.volume_2.name')}"
    mount_point: /home/agent/vol_2
    fs: xfs
    label: vol2
  volume_3:
    ensure: absent
    target_vol: "%{alias('volumes.volume_3.name')}"
    mount_point: /home/agent/vol_3
    fs: xfs
    label: vol3


snapshots:
  snapshot-1:
    ensure: present