---

version: 5

defaults:
  datadir: /etc/puppetlabs/code/environments/%{environment}/hieradata
  data_hash: eyaml_lookup_key

hierarchy:
  - name: "Secret's"
    path: "secure.yaml"
    lookup_key: eyaml_lookup_key
    options:
        pkcs7_private_key: /etc/puppetlabs/keys/private_key.pkcs7.pem
        pkcs7_public_key: /etc/puppetlabs/keys/public_key.pkcs7.pem

  - name: "Other"
    path: "common.yaml"
    data_hash: yaml_data

  - name: "Per-node data"
    path: "nodes/%{fqdn}.yaml"
    data_hash: yaml_data
